name: Reset to working commit

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset to 21de705
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git reset --hard 21de705
          git push --force origin main
